name: CD_front Pipeline

# Information about the event that triggers the workflow
on:
  workflow_run:
    workflows: ['ci_front']
    branches: [jfra_frontend_branch]
    types: [completed]

env:
  PORT: 80
  COMMIT_SHA: ${{ github.sha }}
  IMAGE_NAME: emailserver
  CCOMMIT: ${{ github.event.workflow_run.head_sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(echo $CCOMMIT | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -l ubuntu ec2-18-119-164-214.us-east-2.compute.amazonaws.com <<EOF
          sudo docker pull ghcr.io/tech-fellows-snoopjake/${{ env.IMAGE_NAME}}:sha-${{ steps.vars.outputs.sha_short }}
          
          ./detener_contenedor.sh
          
          ls -la
          sudo docker run -d -p ${{ env.PORT }}:80 ghcr.io/valwolfor/${{ env.IMAGE_NAME}}:sha-${{ steps.vars.outputs.sha_short }}
          sudo docker container prune -f
          sudo docker image prune -a 
        EOF