name: ci_back

on:
  push:
    branches:
      - jfra_backend_branch
  pull_request:
    types: [opened, synchronize, reopened] # For the pull request sonarcloud decorators

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write # This permission is added for SonarCloud analysis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones  disabled for SonarCloud compatibility

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Use Git tags as Docker tags
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha

      - name: Set DJango environment variables
        #run: |
        #    echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        #    echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        #    echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        #    echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        #    echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST}}
          DB_PORT: ${{ secrets.DB_PORT}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./EmailBackend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: EmailBackend/
